const path = require('path');
require('dotenv').config({path: path.join(__dirname, '.env')});
console.log('NODE_ENV:', JSON.stringify(process.env.NODE_ENV));
console.log('DB_HOST:', process.env.DB_HOST);
console.log('DB_PORT:', process.env.DB_PORT);
console.log('DB_NAME:', JSON.stringify(process.env.DB_NAME));
console.log('DB_USER:', process.env.DB_USER);
console.log('DB_PASSWORD:', JSON.stringify(process.env.DB_PASSWORD));
console.log('DATABASE_URL:', !!process.env.DATABASE_URL ? 'set' : 'not set');
const loaded = require('dotenv').config({ path: './.env', debug: true });
console.log('.env loaded:', loaded.parsed ? 'YES vars:' + Object.keys(loaded.parsed).length : 'NO ' + (loaded.error || 'loaded'));
